name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  network:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Network
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: RG-backtest-enginge-distributed
          template: ./infra/network.json
          parameters: location=germanywestcentral
          deploymentName: network

  storage:
    needs: network
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Storage
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: RG-backtest-enginge-distributed
          template: ./infra/storage.json
          parameters: location=germanywestcentral storageAccountName=${{ secrets.STORAGE_ACCOUNT_NAME }}
          deploymentName: storage

  database:
    needs: storage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Database
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: RG-backtest-enginge-distributed
          template: ./infra/database.json
          parameters: location=germanywestcentral administratorPassword=${{ secrets.POSTGRES_PASSWORD }}
          deploymentName: database

  compute:
    needs: database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Compute
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: RG-backtest-enginge-distributed
          template: ./infra/compute.json
          parameters: location=germanywestcentral adminPublicKey="${{ secrets.SSH_PUBLIC_KEY }}"
          deploymentName: compute
